# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/yk/Downloads/Greedy-Snake-Verilog-master/Greedy-Snake-Verilog-master/Code/xdc/Nexys4DDR_Master.xdc

# IP: ip/c_counter_binary_3/c_counter_binary_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_counter_binary_3 || ORIG_REF_NAME==c_counter_binary_3} -quiet] -quiet

# IP: ip/c_counter_binary_2/c_counter_binary_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_counter_binary_2 || ORIG_REF_NAME==c_counter_binary_2} -quiet] -quiet

# IP: ip/c_counter_binary_1/c_counter_binary_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_counter_binary_1 || ORIG_REF_NAME==c_counter_binary_1} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
